### ISSUE TITLE
the year is not 205

### ISSUE THREAD

**Issue by ghost** [ChrisCummins/msc-thesis#84]
you have marked the year on [this](https://github.com/ChrisCummins/msc-thesis/tree/master/experiments/205-06-04-train) folder as 205. that is 1810 years ago.

**Comment by ChrisCummins** [comment]
I wrote the code along time ago ;)

**Comment by GTTDD** [comment]
"I'm Chris, a full time geek and re­search stu­dent with a pas­sion for de­vel­op­ing great soft­ware, of­ten late at night. Ask me about open source, Linux, ob­scure LISP dia­lects, or 160's Rus­sian surf­ing rock."
